# Generated by Django 6.0.2 on 2026-02-22 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_pacient_delete_nurse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacient',
            new_name='Patient',
        ),
    ]
