# Generated by Django 6.0.2 on 2026-02-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_rename_pacient_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.patient')),
            ],
        ),
    ]
