# Generated by Django 6.0.2 on 2026-02-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_medical_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.medical_task')),
            ],
            options={
                'unique_together': {('task', 'status')},
            },
        ),
    ]
