# Generated by Django 6.0.2 on 2026-02-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_task',
            name='owner',
        ),
    ]
