# Generated by Django 6.0.2 on 2026-02-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_remove_medical_task_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_status',
            old_name='status',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task_status',
            old_name='task',
            new_name='habit',
        ),
        migrations.AlterUniqueTogether(
            name='task_status',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task_status',
            name='date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Habit_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.patient')),
            ],
        ),
        migrations.AddField(
            model_name='task_status',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupon.habit_table'),
            preserve_default=False,
        ),
    ]
